project:
  type: website
  output-dir: docs

website:
  title: "gabrielleeshaorei.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - diary.qmd
        

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    
    

editor: visual

